rules = [
  OrganizeImports,
  DisableSyntax,
  LeakingImplicitClassVal,
  NoValInForComprehension,
  RedundantSyntax
]

OrganizeImports {
  groupedImports = Merge
  groups = [
    "*"
    "javax."
    "java."
    "scala."
  ]
}
